<!-- Store Locator hit template -->
<script type="text/template" id="autocomplete_store_locator_template">

    <div>
        <span>{{store_name}}</span><span> | </span>
        <span>{{store_phone}}</span><span> | </span>
        <span>{{store_address}}</span><span> | </span>
        <span>{{store_city}}</span><span> | </span>
        <span>{{store_state}}</span><span> | </span>
        <span>{{store_zip}}</span><span> | </span>
        <span>{{store_country}}</span>
    </div>

</script>